project setup
Danny-imo/portfolio pull request #1
Opened 2023-03-22 14:34 UTC by Danny-imo

### **In This Branch:**

- [ ] Added Linters
- [ ] Added HTML
- [ ] Added CSS

2023-03-22 15:00 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 
- Descriptive PR and commit messages :+1: 


## Required Changes ♻️
- [ REQUIRED] Kindly make sure your README file is customized with your own data considering only the FAQ section optional and removing/replacing the Microverse logo :recycle: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 20:53 UTC, braincee requested changes
Hello @Danny-imo  ✋, I am @braincee your Code Reviewer

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


![so-close](https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif)

HIGHLIGHTS
------

 - GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅

REQUIRED CHANGES ♻️
------

- [ ] Please ensure that you add setup instructions to the README file for other developers to clone the repository. Example: `https://github.com/Danny-imo/portfolio.git`
- [ ] Kindly update the MIT with a link to the MIT file in your README file.
- [ ] KIndly add a specific installation process in the README file. Example `npm install`.
- [ ] KIndly add social media links to the author section. Example Twitter, LinkedIn and Facebook

**_Please check the comments under the review._**

OPTIONAL CHANGES
--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 20:53 UTC, braincee commented on README.md
>  - [Live Demo Link](https://google.com)
- [ ] [OPTIONAL] I kindly suggest to remove the live demo link since the project has not been deployed yet

2023-03-22 20:53 UTC, braincee commented on README.md
>  ### Prerequisites
- [ ] [OPTIONAL] I kindly suggest adding some prerequisites to the README file to look professional
Example:
- Have some knowledge of HTML and CSS
- Be familiar with git commands
- Basics understanding of Linters

2023-03-23 10:46 UTC, Shedrack-Sunday approved these changes
# STATUS: APPROVED ♻️♻️
Hi @Danny-imo 

To highlight 👍🏽
✔️ Proper use of .gitignore
✔️ No linter errors

Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-23 10:46 UTC, Shedrack-Sunday commented on README.md
>  - [ ] **[new_feature_2]**
- [Optional] Please add three future features to this section of the README to show possibilities of possible features in the future 👍

2023-03-23 10:46 UTC, Shedrack-Sunday commented on README.md
>  _NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [Optional] This sectio was meant to help and give a guide. Kindly delete it

2023-03-23 10:53 UTC, merged