Contactform
Danny-imo/portfolio pull request #6
Opened 2023-03-30 15:21 UTC by Danny-imo

- [ ] Add linters
- [ ] Add placeholders
- [ ] Add contact form
- [ ] Add background color

2023-04-04 12:45 UTC, amejid reviewed
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, where linter checks are not running. Kindly solve the merge conflict and make sure linter checks are running properly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-05 20:58 UTC, adel-gu reviewed
# Status: INVALID ❌ 

**Hi @ 👋🏼  **

While you made a great effort 💪🏼💪🏼💪🏼 in this project, unfortunately, I cannot proceed to review your code.

![](https://media4.giphy.com/media/YiKiqMTzrQZwmF4I5N/giphy.gif?cid=ecf05e47ivb4maszhycmcz2u9edemspx9htkiskyfkzok3xz&rid=giphy.gif&ct=g)

## Invalid Code Review Request

You have submitted a project, that misses the linter checks probably because the linter.yml contain some issues so please consider copying the exact file from [linter-config](https://github.com/microverseinc/linters-config) and try again 👏🏼 

![Screenshot from 2023-04-05 21-48-28](https://user-images.githubusercontent.com/68030297/230209900-61d4d327-0cba-4d35-ac4a-7037ff91fabb.png)
![Screenshot from 2023-04-05 21-58-04](https://user-images.githubusercontent.com/68030297/230209975-9b7700d5-f506-438c-a65f-fe14f9f84e19.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-06 10:47 UTC, levy002 requested changes
## Hello @Danny-imo   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter errors :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 10:47 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure the border of the `Get in touch` button matches the provided Figma design.
- [ ] Kindly make sure to change the typography on the `Get in touch` button in order to match the provided Figma design. Kindly adjust your `font-weight` and `font-size`

     - ### YOUR DESIGN
     
     ![image](https://user-images.githubusercontent.com/87197412/230352735-4d0abeee-1080-4cdf-8556-21acba31ec97.png)

     - ### FIGMA DESIGN
    ![image](https://user-images.githubusercontent.com/87197412/230352924-4b0580c8-3af2-44ff-b47b-77284396add5.png)

2023-04-06 10:47 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure the contact section is aligned well on the page in order to match the provided Figma design.

- [OPTIONAL] Kindly make sure to align the rest part of your Portfolio correctly in order to match the provided Figma design.

 - ### YOUR
    ![screencapture-127-0-0-1-5500-index-html-2023-04-06-12_41_32](https://user-images.githubusercontent.com/87197412/230354165-80494cb4-25a7-4a98-a1f0-37de8bf53467.png)
 DESIGN
 
 - ### FIGMA DESIGN
![image](https://user-images.githubusercontent.com/87197412/230354844-e5c5c066-67ba-4637-900a-d5e5b410bf64.png)

2023-04-06 16:07 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/xT0BKhunZXlEsnpz7q/giphy.gif)

# Hi @Danny-imo 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 16:07 UTC, AbelG101 commented on style.css
> +}
- [ ] [OPTIONAL] Great job 👏 fixing the button styling but please make sure the spacing between the form elements looks similar to the given FIgma design as this ensures your future clients that you can implement a given design down to the last pixel.
    - Your design:
      ![image](https://user-images.githubusercontent.com/104968236/230435040-79106c14-3d82-4b00-bdce-1d22562c0032.png)
    - Figma design:
      ![image](https://user-images.githubusercontent.com/104968236/230435346-337801a8-5501-400f-80d9-5a43cd64e5ae.png)

2023-04-06 19:39 UTC, merged